version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expondo a porta padrão do MongoDB
    volumes:
      - mongo_data:/data/db
    networks:
      - iot_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"  # Expondo a porta padrão do Redis
    volumes:
      - redis_data:/data
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
